CREATE DATABASE friends_db;
USE friends_db;

CREATE TABLE `friends` (
	`id` int NOT NULL AUTO_INCREMENT,
	`name` varchar(255) NOT NULL,
    `photoURL` VARCHAR(255) NOT NULL,
	`Q1` INTEGER(10) NOT NULL,
    `Q2` INTEGER(10) NOT NULL,
    `Q3` INTEGER(10) NOT NULL,
    `Q4` INTEGER(10) NOT NULL,
    `Q5` INTEGER(10) NOT NULL,
    `Q6` INTEGER(10) NOT NULL,
    `Q7` INTEGER(10) NOT NULL,
    `Q8` INTEGER(10) NOT NULL,
    `Q9` INTEGER(10) NOT NULL,
    `Q10` INTEGER(10) NOT NULL,

	PRIMARY KEY (`id`)
);